name: Keep to Notion Sync

on:
  schedule:
    - cron: "0 1 * * *" # 每天凌晨 1 点自动同步
  workflow_dispatch: # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run keep to notion script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          KEEP_MOBILE: ${{ secrets.KEEP_MOBILE }}
          KEEP_PASSWORD: ${{ secrets.KEEP_PASSWORD }}
        run: |
          python sync_keep_to_notion.py
