name: Keep to Notion Sync

on:
  schedule:
    - cron: "0 20,1 * * *"  # 每天北京时间早上 4 点和晚上 9 点（UTC 时间）
  workflow_dispatch: # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug env
        run: |
          echo "🔍 环境变量检查："
          echo "NOTION_DATABASE_ID=${{ secrets.NOTION_DATABASE_ID }}"
          echo "KEEP_MOBILE=${{ secrets.KEEP_MOBILE }}"
          echo "✅ Secrets 注入成功，准备运行同步脚本"

      - name: Run keep to notion script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          KEEP_MOBILE: ${{ secrets.KEEP_MOBILE }}
          KEEP_PASSWORD: ${{ secrets.KEEP_PASSWORD }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}  # 保留 OpenWeather API 密钥
        run: |
          python sync_keep_to_notion.py


