name: Keep to Notion Sync

on:
  schedule:
    - cron: "0 1 * * *"  # 每天凌晨 1 点自动同步（UTC 时间 -> 北京时间早上 9 点）
  workflow_dispatch:      # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ✅ 创建 .env 文件
        run: |
          echo "NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}" >> .env
          echo "NOTION_DATABASE_ID=${{ secrets.NOTION_DATABASE_ID }}" >> .env
          echo "KEEP_MOBILE=${{ secrets.KEEP_MOBILE }}" >> .env
          echo "KEEP_PASSWORD=${{ secrets.KEEP_PASSWORD }}" >> .env

      - name: Run keep to notion script
        run: python sync_keep_to_notion.py
