name: Weather Sync

on:
  schedule:
    - cron: "0 3 * * *"  # 每天北京时间 03:00
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv notion-client  # 安装依赖

      - name: Run keep to notion script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          KEEP_MOBILE: ${{ secrets.KEEP_MOBILE }}
          KEEP_PASSWORD: ${{ secrets.KEEP_PASSWORD }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}  # 保留 OpenWeather API 密钥
        run: |
          python sync_keep_to_notion.py
